### ISSUE TITLE
good luck ❤️

### ISSUE THREAD

**Issue by wass3r** [werelord/adventofcode2022#1]
long time no see 😄 didn't know you were doing stuff in Go 🐹!

![disappear](https://user-images.githubusercontent.com/1301201/205974051-5850ac87-a434-4150-8289-b354161ae86b.gif)

**Comment by werelord** [comment]
hey.. yeah, been playing around with go for a while.. some things I like, others I don't.. 

Might end up doing other years in other languages.. If I ever decide to tackle rust.. :p

**Comment by wass3r** [comment]
good to hear from you. yes, rust is on the list for me as well.. one of those you just gotta dive in and deal with the pain. AoC seems appropriate for learning if you're not trying to claim top spots on leaderboards :)

saw some guy streaming and doing these in SQLite 😵‍💫

**Comment by werelord** [comment]
day 8, yeah, was kinda thinking it could work.. if your sql foo is good..

There's no way I'll even try for the leaderboards.. the type of person that goes for speed coding/competition is not me...
